################################################################################
# Joshua C. Fjelstul, Ph.D.
# cjeujudges R package
# automatically generated by the codebookr R package
################################################################################

#' Data on the backgrounds of CJEU judges
#' 
#' This dataset includes data on professional backgrounds of all judges at the
#' Court of Justice (1953-2021) and the General Court (1989-2021). The sources
#' of the data are the judges' official biographies, which are published
#' online by the Court. There is one observation per biographical item per
#' judge. The dataset indicates whether each item relates to the judge's
#' education, the judge's prior professional experience, or some other
#' category of biographical information (such as membership in a professional
#' society or professional accomplishments). For items related to a judge's
#' professional experience, the dataset indicates whether the judge was a
#' judge (at a different court), a lawyer, a civil servant, an academic, or a
#' politician. For items related to prior experience as a judge, the dataset
#' indicates whether the court was a lower court, a high court, the CJEU, or
#' another international court.
#' 
#' @format A data frame with 23 variables:
#' \describe{
#' \item{key_id}{\code{numeric}. An ID number that uniquely identifies each
#' observation. Indicates the default sort order for the dataset.}
#' \item{iuropa_judge_id}{\code{string}. An ID number that uniquely identifies
#' each judge in the format \code{J:####}. The first two digits are the member
#' state ID, with a leading 0 if necessary. The second two digits uniquely
#' identify the judge within the member state. The number is assigned with the
#' judges sorted chronologically by date of appointment and then
#' alphabetically by last name. }
#' \item{item_id}{\code{string}. An ID number that uniquely identifies each
#' biography item in the format \code{J:####:##}. This number is the judge ID
#' followed by the number of the item, with a leading 0 if necessary.}
#' \item{first_name}{\code{string}. The first name of the judge. }
#' \item{last_name}{\code{string}. The last name of the judge.}
#' \item{last_name_latin}{\code{string}. The last name of the judge using only
#' basic Latin characters (to avoid character-encoding problems).}
#' \item{last_name_label}{\code{string}. A label (for making visualizations)
#' that differentiates between judges with the same last name by adding the
#' judge's first initial.}
#' \item{last_name_latin_label}{\code{string}. A label (for making
#' visualizations) using only basic Latin characters (to avoid
#' character-encoding problems) that differentiates between judges with the
#' same last name by adding the judge's first initial.}
#' \item{item_number}{\code{numeric}. The number of the item in the judge's
#' biography.}
#' \item{item_text}{\code{string}. The text of the bibliography item.}
#' \item{type_education}{\code{dummy}. A dummy variable indicating whether the
#' item relates to the judge's education.}
#' \item{type_job}{\code{dummy}. A dummy variable indicating whether the item
#' relates to the judge's prior professional experience.}
#' \item{type_other}{\code{dummy}. A dummy variable indicating whether the
#' item relates to some other biographical information, such as membership in
#' a professional organization or a professional accomplishment. }
#' \item{job_judge}{\code{dummy}. A dummy variable indicating whether the item
#' says that the judge has prior experience as a lawyer. Coded \code{0} if
#' \code{type_job} is not coded \code{1}.}
#' \item{job_lawyer}{\code{dummy}. A dummy variable indicating whether the
#' item says that the judge has prior experience as a judge. Coded \code{0} if
#' \code{type_job} is not coded \code{1}.}
#' \item{job_civil_servant}{\code{dummy}. A dummy variable indicating whether
#' the item says that the judge has prior experience as a civil servant. Coded
#' \code{0} if \code{type_job} is not coded \code{1}.}
#' \item{job_academic}{\code{dummy}. A dummy variable indicating whether the
#' item says that the judge has prior experience as an academic. Coded
#' \code{0} if \code{type_job} is not coded \code{1}.}
#' \item{job_politician}{\code{dummy}. A dummy variable indicating whether the
#' item says that the judge has prior experience as a politician. Coded
#' \code{0} if \code{type_job} is not coded \code{1}.}
#' \item{court_lower}{\code{dummy}. A dummy variable indicating whether the
#' item says that the judge has prior experience as a judge at a lower court.
#' Coded \code{0} if \code{job_judge} is not coded \code{1}.}
#' \item{court_high}{\code{dummy}. A dummy variable indicating whether the
#' item says that the judge has prior experience as a judge at a high court.
#' Coded \code{0} if \code{job_judge} is not coded \code{1}.}
#' \item{court_cjeu}{\code{dummy}. A dummy variable indicating whether the
#' item says that the judge has prior experience as a judge or an Advocate
#' General at the CJEU. Coded \code{0} if \code{job_judge} is not coded
#' \code{1}.}
#' \item{court_international}{\code{dummy}. A dummy variable indicating
#' whether the item says that the judge has prior experience as a judge at an
#' international court (excluding the CJEU). Coded \code{0} if
#' \code{job_judge} is not coded \code{1}.}
#' \item{common_law_university}{\code{dummy}. A dummy variable indicating
#' whether the item mentions a common law university.}
#' }
"judge_backgrounds"

################################################################################
# end R script
################################################################################

